# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from signup import Ui_Dialog2
from welcome_1 import Ui_Form
import sqlite3
conn=sqlite3.connect('TheGameHub.db')
curs=conn.cursor()

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(358, 300)
        Dialog.setStyleSheet("background-color: rgb(233, 255, 250);")
        self.formLayout = QtWidgets.QFormLayout(Dialog)
        self.formLayout.setContentsMargins(30, 20, 30, -1)
        self.formLayout.setHorizontalSpacing(50)
        self.formLayout.setVerticalSpacing(30)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.label_3.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.label_4)
        self.u_name_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.u_name_label.setFont(font)
        self.u_name_label.setObjectName("u_name_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.u_name_label)
        self.uname_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.uname_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.uname_lineEdit.setObjectName("uname_lineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.uname_lineEdit)
        self.password_label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.password_label)
        self.password_lineEdit = QtWidgets.QLineEdit(Dialog)
        self.password_lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_lineEdit.setText("")
        self.password_lineEdit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineEdit.setObjectName("password_lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.password_lineEdit)
        self.OK = QtWidgets.QPushButton(Dialog)
        self.OK.setStyleSheet("background-color: rgb(225, 225, 255);")
        self.OK.setObjectName("OK")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.OK)
        self.Register = QtWidgets.QPushButton(Dialog)
        self.Register.setStyleSheet("background-color: rgb(225, 225, 255);")
        self.Register.setObjectName("Register")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.Register)

        self.OK.clicked.connect(self.loginCheck)
        self.Register.clicked.connect(self.signupshow)
        
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Log In"))
        self.label_3.setText(_translate("Dialog", "WELCOME TO THE GAME HUB"))
        self.label_4.setText(_translate("Dialog", "PLEASE LOGIN / REGISTER"))
        self.u_name_label.setText(_translate("Dialog", "username:"))
        self.password_label.setText(_translate("Dialog", "password:"))
        self.OK.setText(_translate("Dialog", "OK"))
        self.Register.setText(_translate("Dialog", "Register"))

    def mainprojectwindowshow(self):
        self.mainwindow = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.mainwindow)
        self.mainwindow.show()
        Dialog.close()

    def signupshow(self):
        self.signupwindow = QtWidgets.QDialog()
        self.ui = Ui_Dialog2()
        self.ui.setupUi(self.signupwindow)
        self.signupwindow.show()

    def loginCheck(self):
        username = self.uname_lineEdit.text()
        password = self.password_lineEdit.text()
        result = curs.execute("SELECT * FROM Users WHERE Username = ? AND Password = ?",(username,password))
        if( len(result.fetchall()) > 0):
            print("user found")            
            self.mainprojectwindowshow()
        elif len(username) == 0 or len(password) == 0:
            if len(username) == 0 and len(password) == 0:
                msg = QMessageBox()
                msg.setWindowTitle("Warning")
                msg.setText('''Please enter username and password''')
                msg.setIcon(QMessageBox.Warning)
                x=msg.exec()
                self.uname_lineEdit.setText("")
                self.password_lineEdit.setText("")
            elif len(username) == 0:                
                msg = QMessageBox()
                msg.setWindowTitle("Warning")
                msg.setText('''Please enter username''')
                msg.setIcon(QMessageBox.Warning)
                x=msg.exec()
                self.uname_lineEdit.setText("")
                self.password_lineEdit.setText("")
            elif len(password) == 0:                
                msg = QMessageBox()
                msg.setWindowTitle("Warning")
                msg.setText('''Please enter password''')
                msg.setIcon(QMessageBox.Warning)
                x=msg.exec()
                self.uname_lineEdit.setText("")
                self.password_lineEdit.setText("")
            
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Warning")
            msg.setText('''Incorrect credentials!
If new user, please register.''')
            msg.setIcon(QMessageBox.Warning)
            x=msg.exec()
            self.uname_lineEdit.setText("")
            self.password_lineEdit.setText("")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
