# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deleteteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3
conn=sqlite3.connect('TheGameHub.db')
curs=conn.cursor()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(325, 416)
        MainWindow.setStyleSheet("background-color: rgb(146, 203, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, 12, -1, 2)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.players_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.players_label.setFont(font)
        self.players_label.setObjectName("players_label")
        self.gridLayout.addWidget(self.players_label, 2, 0, 1, 1)
        self.choose_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.choose_label.setFont(font)
        self.choose_label.setObjectName("choose_label")
        self.gridLayout.addWidget(self.choose_label, 0, 0, 1, 1)
        self.players_list = QtWidgets.QListWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.players_list.setFont(font)
        self.players_list.setStyleSheet("background-color: rgb(207, 255, 185);")
        self.players_list.setObjectName("players_list")
        self.gridLayout.addWidget(self.players_list, 4, 0, 1, 1)
        self.cb_delete = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.cb_delete.setFont(font)
        self.cb_delete.setStyleSheet("background-color: rgb(230, 230, 230);")
        self.cb_delete.setObjectName("cb_delete")
        self.cb_delete.addItem("")
        self.gridLayout.addWidget(self.cb_delete, 1, 0, 1, 1)
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(246, 255, 137))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.delete_btn.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.delete_btn.setFont(font)
        self.delete_btn.setStyleSheet("background-color: rgb(246, 255, 137);")
        self.delete_btn.setObjectName("delete_btn")
        self.gridLayout.addWidget(self.delete_btn, 8, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.cb_delete.activated.connect(self.load_players)
        self.load_teams()
        self.delete_btn.clicked.connect(self.delete_team)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Delete Team"))
        self.players_label.setText(_translate("MainWindow", "Team Players:"))
        self.choose_label.setText(_translate("MainWindow", "Choose Team To Delete:"))
        self.cb_delete.setItemText(0, _translate("MainWindow", "SELECT TEAM"))
        self.delete_btn.setText(_translate("MainWindow", "Delete Team"))

    def load_teams(self):
        self.cb_delete.clear()
        curs.execute('SELECT Name from Teams;')           
        Teams = curs.fetchall()
        l=len(Teams)
        self.cb_delete.addItem("SELECT TEAM")
        for i in range(0,l):
            row=Teams[i]
            team=row[0]
            self.cb_delete.addItem(team)

    def load_players(self, i):
        self.players_list.clear()
        txt = self.cb_delete.itemText(i)
        if txt != "SELECT TEAM":
            curs.execute('SELECT Players from Teams WHERE Name="{}";'.format(txt))
            rec=curs.fetchone()        
            players = self.string_to_list(rec[0])        
            self.players_list.addItems(players)
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Warning")
            msg.setText("Invalid Selection.")
            msg.setIcon(QMessageBox.Warning)
            x=msg.exec()

    def string_to_list(self,string):        
        items = []
        item = ""
        itemExpected = True
        for char in string[1:]:
            if itemExpected and char not in ["]", ",", "[", "'"]:
                item += char                
            elif char in [",", "[", "]"]:
                itemExpected = True
                items.append(item)
                item = ""
        i=1
        for txt in items[1:]:
            items[i]=txt[1:]
            i+=1
            if i==12:break
        return items
    
    def delete_team(self):
        txt=self.cb_delete.currentText()
        try:
            curs.execute('DELETE FROM Teams WHERE Name="{}";'.format(txt))
            conn.commit()
            msg = QMessageBox()
            msg.setWindowTitle("The Game Hub")
            msg.setText("Your team is deleted.")
            msg.setIcon(QMessageBox.Information)
            x=msg.exec()
            self.players_list.clear()
            self.load_teams()
        except:
            msg5 = QMessageBox()
            msg5.setWindowTitle("The Game Hub")
            msg5.setText("Error in operation.")
            msg5.setIcon(QMessageBox.Warning)
            w=msg5.exec()
            conn.rollback()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
