# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'leaderboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
conn=sqlite3.connect('TheGameHub.db')
curs=conn.cursor()

class Ui_Score(object):
        
    def setupUi(self, Score):
        Score.setObjectName("Score")
        Score.resize(453, 465)
        Score.setStyleSheet("background-color: rgb(255, 148, 221);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Score)
        self.verticalLayout.setContentsMargins(20, -1, 20, -1)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLineEdit(Score)
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(20)
        self.label_1.setFont(font)
        self.label_1.setStyleSheet("background-color: rgb(57, 255, 149);")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setReadOnly(True)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.rank_table = QtWidgets.QTableWidget(Score)
        self.rank_table.setMinimumSize(QtCore.QSize(413, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.rank_table.setFont(font)
        self.rank_table.setStyleSheet("background-color: rgb(192, 255, 232);")
        self.rank_table.setRowCount(0)
        self.rank_table.setColumnCount(3)
        self.rank_table.setObjectName("rank_table")
        item = QtWidgets.QTableWidgetItem()
        self.rank_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.rank_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.rank_table.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.rank_table)
        self.pushButton = QtWidgets.QPushButton(Score)
        self.pushButton.setStyleSheet("background-color: rgb(188, 249, 255);")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.b_team_label = QtWidgets.QLineEdit(Score)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.b_team_label.setFont(font)
        self.b_team_label.setStyleSheet("background-color: rgb(161, 107, 255);")
        self.b_team_label.setAlignment(QtCore.Qt.AlignCenter)
        self.b_team_label.setReadOnly(True)
        self.b_team_label.setObjectName("b_team_label")
        self.horizontalLayout.addWidget(self.b_team_label)
        self.best_team = QtWidgets.QLineEdit(Score)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.best_team.setFont(font)
        self.best_team.setStyleSheet("background-color: rgb(161, 107, 255);")
        self.best_team.setAlignment(QtCore.Qt.AlignCenter)
        self.best_team.setReadOnly(True)
        self.best_team.setObjectName("best_team")
        self.horizontalLayout.addWidget(self.best_team)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.bestTeam()
        self.pushButton.clicked.connect(self.loadData)

        self.retranslateUi(Score)
        QtCore.QMetaObject.connectSlotsByName(Score)

    def retranslateUi(self, Score):
        _translate = QtCore.QCoreApplication.translate
        Score.setWindowTitle(_translate("Score", "Leaderboard"))
        self.label_1.setText(_translate("Score", "POINTS   TABLE"))
        item = self.rank_table.horizontalHeaderItem(0)
        item.setText(_translate("Score", "TEAM NAME"))
        item = self.rank_table.horizontalHeaderItem(1)
        item.setText(_translate("Score", "POINTS USED"))
        item = self.rank_table.horizontalHeaderItem(2)
        item.setText(_translate("Score", "TEAM SCORE"))
        self.pushButton.setText(_translate("Score", "Show Rank"))
        self.b_team_label.setText(_translate("Score", "BEST PERFORMER"))

    def loadData(self):
        curs.execute("SELECT Name,Value,Score FROM Teams ORDER BY Score desc")
        result = curs.fetchall()
        self.rank_table.setRowCount(0)
        for row_number, row_data in enumerate(result):
            self.rank_table.insertRow(row_number)
            for column_number, data in enumerate(row_data):                
                self.rank_table.setItem(row_number, column_number, QtWidgets.QTableWidgetItem(str(data)))           
        self.best_team.setText(self.temp)
        
    def bestTeam(self):
        curs.execute("SELECT Name FROM Teams WHERE Score=(SELECT MAX(Score)FROM Teams);")
        result = curs.fetchone()
        self.temp = str(result[0])

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Score = QtWidgets.QWidget()
    ui = Ui_Score()
    ui.setupUi(Score)
    Score.show()
    sys.exit(app.exec_())
