# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'openteam.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3
conn=sqlite3.connect('TheGameHub.db')
curs=conn.cursor()

class Ui_opendialog(object):
    def setupUi(self, opendialog):
        opendialog.setObjectName("opendialog")
        opendialog.resize(335, 400)
        self.centralwidget = QtWidgets.QWidget(opendialog)
        self.centralwidget.setStyleSheet("background-color: rgb(219, 255, 196);")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.openteam = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.openteam.setFont(font)
        self.openteam.setObjectName("openteam")
        self.gridLayout.addWidget(self.openteam, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.cb_open = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setBold(True)
        font.setWeight(75)
        self.cb_open.setFont(font)
        self.cb_open.setStyleSheet("background-color: rgb(189, 255, 251);")
        self.cb_open.setObjectName("cb_open")
        self.cb_open.addItem("")
        self.gridLayout.addWidget(self.cb_open, 1, 0, 1, 1)
        self.list_open = QtWidgets.QListWidget(self.centralwidget)
        self.list_open.setStyleSheet("background-color: rgb(255, 255, 238);")
        self.list_open.setObjectName("list_open")
        self.gridLayout.addWidget(self.list_open, 4, 0, 1, 1)
        opendialog.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(opendialog)
        self.statusbar.setObjectName("statusbar")
        opendialog.setStatusBar(self.statusbar)

        self.cb_open.activated.connect(self.load_players)
        self.load_team()

        self.retranslateUi(opendialog)
        QtCore.QMetaObject.connectSlotsByName(opendialog)

    def retranslateUi(self, opendialog):
        _translate = QtCore.QCoreApplication.translate
        opendialog.setWindowTitle(_translate("opendialog", "Open Team"))
        self.openteam.setText(_translate("opendialog", "Choose a team:"))
        self.label.setText(_translate("opendialog", "Team players:"))
        self.cb_open.setItemText(0, _translate("opendialog", "SELECT TEAM"))

    def load_team(self):
        curs.execute('SELECT Name from Teams;')           
        Teams = curs.fetchall()
        l=len(Teams)
        for i in range(0,l):
            row=Teams[i]
            team=row[0]
            self.cb_open.addItem(team)

    def load_players(self):
        self.list_open.clear()
        txt=self.cb_open.currentText()
        if txt != "SELECT TEAM":
            curs.execute('SELECT Players from Teams WHERE Name="{}";'.format(txt))
            rec=curs.fetchone()        
            players = self.string_to_list(rec[0])        
            self.list_open.addItems(players)
        else:
            msg = QMessageBox()
            msg.setWindowTitle("The Game Hub")
            msg.setText("Invalid Selection.")
            msg.setIcon(QMessageBox.Warning)
            x=msg.exec()

    def string_to_list(self,string):        
        items = []
        item = ""
        itemExpected = True
        for char in string[1:]:
            if itemExpected and char not in ["]", ",", "[", "'"]:
                item += char                
            elif char in [",", "[", "]"]:
                itemExpected = True
                items.append(item)
                item = ""
        i=1
        for txt in items[1:]:
            items[i]=txt[1:]
            i+=1
            if i==12:break
        return items
    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    opendialog = QtWidgets.QMainWindow()
    ui = Ui_opendialog()
    ui.setupUi(opendialog)
    opendialog.show()
    sys.exit(app.exec_())
