# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from evaluate import Ui_MainWindow2
from leaderboard import Ui_Score
from teamSelection import Ui_OtherWindow
from deleteteam import Ui_MainWindow
from openteam import Ui_opendialog
from editTeam import Ui_OtherWindow1
import sqlite3
conn=sqlite3.connect('TheGameHub.db')
curs=conn.cursor()

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(761, 480)
        Form.setStyleSheet("background-image: url(:/newPrefix/Cap.JPG);")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(40, 20, 40, 46)
        self.gridLayout.setHorizontalSpacing(150)
        self.gridLayout.setVerticalSpacing(100)
        self.gridLayout.setObjectName("gridLayout")
        self.welcome_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.welcome_label.setFont(font)
        self.welcome_label.setStyleSheet("background-color: rgb(149, 201, 214);")
        self.welcome_label.setTextFormat(QtCore.Qt.RichText)
        self.welcome_label.setAlignment(QtCore.Qt.AlignCenter)
        self.welcome_label.setObjectName("welcome_label")
        self.gridLayout.addWidget(self.welcome_label, 0, 0, 1, 5)
        spacerItem = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 1)
        self.select_label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.select_label.setFont(font)
        self.select_label.setAlignment(QtCore.Qt.AlignCenter)
        self.select_label.setObjectName("select_label")
        self.gridLayout.addWidget(self.select_label, 1, 1, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 4, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(40, -1, 0, -1)
        self.verticalLayout.setSpacing(30)
        self.verticalLayout.setObjectName("verticalLayout")
        self.newTeam_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.newTeam_btn.setFont(font)
        self.newTeam_btn.setObjectName("newTeam_btn")
        self.verticalLayout.addWidget(self.newTeam_btn)
        self.openTeam_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.openTeam_btn.setFont(font)
        self.openTeam_btn.setObjectName("openTeam_btn")
        self.verticalLayout.addWidget(self.openTeam_btn)
        self.evaluateTeam_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.evaluateTeam_btn.setFont(font)
        self.evaluateTeam_btn.setObjectName("evaluateTeam_btn")
        self.verticalLayout.addWidget(self.evaluateTeam_btn)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 2)
        spacerItem2 = QtWidgets.QSpacerItem(14, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 2, 2, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(0, -1, 40, -1)
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.deleteTeam_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.deleteTeam_btn.setFont(font)
        self.deleteTeam_btn.setObjectName("deleteTeam_btn")
        self.verticalLayout_2.addWidget(self.deleteTeam_btn)
        self.leaderBoard_btn = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.leaderBoard_btn.setFont(font)
        self.leaderBoard_btn.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.leaderBoard_btn.setObjectName("leaderBoard_btn")
        self.verticalLayout_2.addWidget(self.leaderBoard_btn)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 3, 1, 2)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 5)
        self.gridLayout.setColumnStretch(2, 5)
        self.gridLayout.setColumnStretch(3, 5)
        self.gridLayout.setColumnStretch(4, 4)
        self.gridLayout.setRowStretch(0, 5)
        self.gridLayout.setRowStretch(1, 2)
        self.gridLayout.setRowStretch(2, 5)

        self.newTeam_btn.clicked.connect(self.create_team)
        self.openTeam_btn.clicked.connect(self.open_team)
        self.pushButton_8.clicked.connect(self.edit_team)
        self.evaluateTeam_btn.clicked.connect(self.evaluate_team)
        self.deleteTeam_btn.clicked.connect(self.delete_team)
        self.leaderBoard_btn.clicked.connect(self.team_scores)
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "The Game Hub"))
        self.welcome_label.setText(_translate("Form", "WELCOME TO THE GAME HUB"))
        self.select_label.setText(_translate("Form", "SELECT YOUR OPERATION:"))
        self.newTeam_btn.setText(_translate("Form", "NEW  Team"))
        self.newTeam_btn.setShortcut(_translate("Form", "Ctrl+N"))
        self.openTeam_btn.setText(_translate("Form", "OPEN Team"))
        self.openTeam_btn.setShortcut(_translate("Form", "Ctrl+O"))
        self.evaluateTeam_btn.setText(_translate("Form", "EVALUATE Team"))
        self.evaluateTeam_btn.setShortcut(_translate("Form", "Ctrl+E"))
        self.pushButton_8.setText(_translate("Form", "EDIT Team"))
        self.deleteTeam_btn.setText(_translate("Form", "DELETE Team"))
        self.leaderBoard_btn.setText(_translate("Form", "LEADERBOARD"))

    def team_scores(self):
        curs.execute('SELECT Name FROM Teams;')
        teams = curs.fetchall()
        if teams != [] :
            self.rankWindow = QtWidgets.QWidget()
            self.ui = Ui_Score()
            self.ui.setupUi(self.rankWindow)
            self.rankWindow.show()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("The Game Hub")
            msg.setText("No team created yet!")
            msg.setIcon(QMessageBox.Information)
            y=msg.exec()

    def evaluate_team(self):
        curs.execute('SELECT Name FROM Teams;')
        teams = curs.fetchall()
        if teams != []:
            self.evaluateWindow = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow2()
            self.ui.setupUi(self.evaluateWindow)
            self.evaluateWindow.show()
        else:
            msg1 = QMessageBox()
            msg1.setWindowTitle("The Game Hub")
            msg1.setText("No team created yet!")
            msg1.setIcon(QMessageBox.Information)
            y=msg1.exec()

    def create_team(self):
        self.selectionWindow = QtWidgets.QMainWindow()
        self.ui = Ui_OtherWindow()
        self.ui.setupUi(self.selectionWindow)
        self.selectionWindow.show()

    def delete_team(self):
        curs.execute('SELECT Name FROM Teams;')
        teams = curs.fetchall()
        if teams != []:
            self.deleteWindow = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.deleteWindow)
            self.deleteWindow.show()
        else:
            msg2 = QMessageBox()
            msg2.setWindowTitle("The Game Hub")
            msg2.setText("No team created yet!")
            msg2.setIcon(QMessageBox.Information)
            y=msg2.exec()

    def open_team(self):
        curs.execute('SELECT Name FROM Teams;')
        teams = curs.fetchall()
        if teams != []:
            self.openWindow = QtWidgets.QMainWindow()
            self.ui = Ui_opendialog()
            self.ui.setupUi(self.openWindow)
            self.openWindow.show()
        else:
            msg3 = QMessageBox()
            msg3.setWindowTitle("The Game Hub")
            msg3.setText("No team created yet!")
            msg3.setIcon(QMessageBox.Information)
            y=msg3.exec()

    def edit_team(self):
        curs.execute('SELECT Name FROM Teams;')
        teams = curs.fetchall()
        if teams != []:
            self.editWindow = QtWidgets.QMainWindow()
            self.ui = Ui_OtherWindow1()
            self.ui.setupUi(self.editWindow)
            self.editWindow.show()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("The Game Hub")
            msg.setText("No team created yet!")
            msg.setIcon(QMessageBox.Information)
            y=msg.exec()

import img

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
